allow disabling the kernel command line
allow disabling the kernel command line

refactor last commit

remove a space

oopsy

oopsy2

pass the arguments properly + proposed refactor

flip true/false in default config

add a warning message

diff --git a/uefi-mkconfig b/uefi-mkconfig
--- a/uefi-mkconfig
+++ b/uefi-mkconfig
@@ -94,22 +94,25 @@ add_uefi_entry () {
 	#Get partition ID
 	partition_id="$(printf "%s\n" "$lsblk_initial_state" | grep "$partition" | cut -d";" -f4)"
 
-	# Add new entry
+	# Prepare parameters for adding new entry
+	local opt_backup_efi
+	local msg_backup_efi
 	if [[ -n $backup_efi ]]; then
-		# When creating backup entry, don't add it to the bootorder
-		if [[ $UMC_TEST == true ]]; then
-			echo "TEST: efibootmgr -q --create-only -b \"$bootnum\" --disk \"/dev/$partition\" --part \"$partition_id\" --label \"$entry_label\" --loader \"${efi_file_path//\//\\}\" -u \"$adding_kernel_commands\""
-		else
-			efibootmgr -q --create-only -b "$bootnum" --disk /dev/"$partition" --part "$partition_id" --label "$entry_label" --loader "${efi_file_path//\//\\}"\
-			-u "$adding_kernel_commands" || die "Failed to add BACKUP UEFI entry for \"$efi_file_path\""
-		fi
+		opt_backup_efi="--create-only"
+		msg_backup_efi="BACKUP "
 	else
-		if [[ $UMC_TEST == true ]]; then
-			echo "TEST: efibootmgr -q --create -b \"$bootnum\" --disk \"/dev/$partition\" --part \"$partition_id\" --label \"$entry_label\" --loader \"${efi_file_path//\//\\}\" -u \"$adding_kernel_commands\""
-		else
-			efibootmgr -q --create -b "$bootnum" --disk /dev/"$partition" --part "$partition_id" --label "$entry_label" --loader "${efi_file_path//\//\\}"\
-			-u "$adding_kernel_commands" || die "Failed to add UEFI entry for \"$efi_file_path\""
-		fi
+		opt_backup_efi="--create"
+	fi
+
+	if [[ -z $DISABLE_CMDLINE ]]; then
+		local opt_cmdline=('-u' "$adding_kernel_commands")
+	fi
+
+	# Add new entry
+	if [[ $UMC_TEST == true ]]; then
+		echo "TEST: efibootmgr -q $opt_backup_efi -b \"$bootnum\" --disk \"/dev/$partition\" --part \"$partition_id\" --label \"$entry_label\" --loader \"${efi_file_path//\//\\}\" ${opt_cmdline[@]}"
+	else
+		efibootmgr -q $opt_backup_efi -b "$bootnum" --disk /dev/"$partition" --part "$partition_id" --label "$entry_label" --loader "${efi_file_path//\//\\}" ${opt_cmdline[@]} || die "Failed to add UEFI ${msg_backup_efi}entry for \"$efi_file_path\""
 	fi
 }
 
@@ -181,17 +184,22 @@ load_config () {
 		
 		echo '# Add your kernel commandline arguments following "; "
 # KERNEL_CONFIG="%entry_id %linux_name Linux %kernel_version ; example=test kernel=test cmdline=test arguments=test"
-KERNEL_CONFIG="%entry_id %linux_name Linux %kernel_version ; "
+KERNEL_CONFIG="%entry_id %linux_name Linux %kernel_version ;"
 
 # Turn on to only add efi files of the latest kernel version
-# ONLY_LATEST=false
+# ONLY_LATEST=true
 
 # Revers order in which entries are added
-# REVERS_ORDER=false
+# REVERS_ORDER=true
 
 # Entry label length limit of 60 characters for better compatibility with UEFI Firmware
 # Can be disabled but thorough testing is recommended before using entry labels longer than 60 characters 
-# ENTRY_LABEL_LIMIT=true' > "/etc/default/uefi-mkconfig"
+# ENTRY_LABEL_LIMIT=false
+
+# Do not insert any kernel command line into the boot entry whatsoever
+# Allows you to build it directly into the kernel without it being overwritten
+# Anything you write into the KERNEL_CONFIG above after the ; will be ignored
+# DISABLE_CMDLINE=true' > "/etc/default/uefi-mkconfig"
 
 		kernel_configs="${default_label} ; "	
 	else
@@ -203,6 +211,9 @@ KERNEL_CONFIG="%entry_id %linux_name Linux %kernel_version ; "
 		
 		# Check if entries should be added in the revers order
 		[[ -n $(grep "REVERS_ORDER=true" "${kernel_config_path}/uefi-mkconfig" | grep -v "#") ]] && REVERS_ORDER=1
+		
+		# Check if we should disable the kernel command line
+		[[ -n $(grep "DISABLE_CMDLINE=true" "${kernel_config_path}/uefi-mkconfig" | grep -v "#") ]] && DISABLE_CMDLINE=1 && ewarn "Warning! DISABLE_CMDLINE option activated. All entries will be added into the firmware without a kernel command line. You should probably configure it somewhere else."
 	fi
 
 	local IFS=$'\n'
